//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by WHO.RC
//
#define IDD_DIALOG1                     101
#define IDI_ICON1                       102
#define ID_TIMER                        200
#define IDC_LIST1                       1000
#define IDC_LIST2                       1001
#define IDC_EDIT1                       1002
#define IDC_EDIT3                       1004
#define IDC_EDIT4                       1005
#define IDC_EDIT5                       1006
#define IDC_BUTTON1                     1007
#define IDC_BUTTON2                     1008
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1009
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
