//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by BINDVIEW.RC
//
#define IDD_DIALOG1                     101
#define IDC_RADIO1                      1000
#define IDC_RADIO2                      1001
#define IDC_RADIO3                      1002
#define IDC_LIST1                       1003
#define IDC_LIST2                       1004
#define IDC_LIST3                       1005
#define IDC_STATIC                      -1
#define IDI_ICON1                       1006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
